# -*- coding: utf-8 -*-
"""shift_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ub4QIUckQcQHafKuLnUwRbV4NiwE1iR
"""

#shift array
#time complexity: O(n)
#Space complexity: O(1)
import random

def shift_elem(int_list, n):
  temp = int_list[0]
  for i in range(n-1):
    int_list[i] = int_list[i + 1]
    #print (f'\n int_list[{i}] = {int_list[i + 1]}')
  int_list[n-1] = temp
      

if __name__ == "__main__":
  print("generating int list...")
  int_list = [*range(0,10)]
  for i in int_list:
    print ("% d"% i, end =", ")

  shift_count = random.randrange(len(int_list))

  print ("\n shift % d"% shift_count)
  for i in range(shift_count):
        print("shifting")
        shift_elem(int_list, len(int_list))

  for i in int_list:
    print ("% d"% i, end =", ")