# -*- coding: utf-8 -*-
"""test_merge_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JB2jfgtFwbuF67JZKDbYrhIDuCMKOXEK
"""

import random

def test_mergeSort():
  import merge_sort
  #
  int_list = random.sample(range(1, 50), 10)
  int_list_copy = int_list.copy()
  assert merge_sort.mergeSort(int_list, 0, len(int_list)-1) == int_list_copy.sort()